### ISSUE TITLE
Incorrect generation of fullchain.pem

### ISSUE THREAD

**Issue by oxman** [acmephp/cli#1]
The library seems to generate a partially wrong fullchain.pem
Because https://www.ssllabs.com said : 
Chain issues	Incomplete, Extra certs, Contains anchor
ISRG Root X1   Not in trust store

Its not a configuration problem, because i tried an other tool to generate certificate and now everything is fine.

**Comment by tgalopin** [comment]
Hi @oxman!

It seems to be a known problem we are actively working on: the Let's Encrypt certificates have been updated and this library is out of date since a few days ago. We are improving the core library with the PR https://github.com/acmephp/core/pull/7 to follow more stricly the ACME spec so this problem should be resolved as soon as this new version will be used in the CLI (and that should be quite soon :) ).

Thanks for your report!

**Comment by tgalopin** [comment]
I close this as the 1.0.0-alpha8 is now based on https://github.com/acmephp/acmephp and is fixing this issue.
